name: Update Dockerhub description

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_REPOSITORY:
        required: true

env:
  HAS_SECRETS: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' && secrets.DOCKERHUB_REPOSITORY != '' }}

jobs:
  update-dockerhub:
    name: Update Dockerhub description
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Hub Description
        if: ${{ env.HAS_SECRETS }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
          readme-filepath: ./dockerhub-description.md
          short-description: 'valkey-bundle installs valkey-server and loads all the valkey modules.'
